PERMS = [
    ("view_dashboard", "可查看 Dashboard"),
    ("view_finance", "可查看 Finance"),
    ("edit_finance", "可編輯 Finance"),
    ("view_projects", "可查看 Projects"),
    ("edit_projects", "可編輯 Projects"),
    ("view_hr", "可查看人資模組"),
    ("edit_hr", "可編輯人資模組"),
    ("delete_hr", "可封存人員資料"),
    ("view_departments", "可查看部門管理"),
    ("edit_departments", "可編輯部門管理"),
    ("delete_departments", "可停用部門"),
    ("view_job_titles", "可查看職稱管理"),
    ("edit_job_titles", "可編輯職稱管理"),
    ("delete_job_titles", "可停用職稱"),
    ("view_employee_movements", "可查看任用異動紀錄"),
    ("edit_employee_movements", "可編輯任用異動紀錄"),
    ("delete_employee_movements", "可刪除任用異動紀錄"),
    ("view_leave", "可查看請假管理"),
    ("edit_leave", "可建立與編輯請假管理"),
    ("approve_leave", "可審核請假"),
    ("delete_leave", "可刪除請假申請"),
    ("delete_leave_types", "可停用請假類型"),
    ("view_attendance", "可查看出勤管理"),
    ("edit_attendance", "可建立與編輯出勤管理"),
    ("delete_attendance", "可刪除出勤紀錄"),
    ("clock_attendance", "可進行上下班打卡"),
    ("admin_users", "可管理使用者"),
    ("admin_roles", "可管理角色"),
    ("view_approvals", "可查看公文簽核模組"),
    ("edit_approvals", "可建立與送出公文"),
    ("approve_documents", "可執行公文簽核"),
    ("manage_approval_templates", "可管理公文模板與簽核流程模板"),
]

DEFAULT_ROLES = {
    "Owner": {
        "description": "全權限",
        "permissions": [code for code, _ in PERMS],
    },
    "Manager": {
        "description": "管理權限",
        "permissions": [
            "view_dashboard",
            "view_finance",
            "edit_finance",
            "view_projects",
            "edit_projects",
            "view_hr",
            "edit_hr",
            "delete_hr",
            "view_departments",
            "edit_departments",
            "delete_departments",
            "view_job_titles",
            "edit_job_titles",
            "delete_job_titles",
            "view_employee_movements",
            "edit_employee_movements",
            "delete_employee_movements",
            "view_leave",
            "edit_leave",
            "approve_leave",
            "delete_leave",
            "delete_leave_types",
            "view_attendance",
            "edit_attendance",
            "delete_attendance",
            "clock_attendance",
            "view_approvals",
            "edit_approvals",
            "approve_documents",
            "manage_approval_templates",
        ],
    },
    "Staff": {
        "description": "一般執行人員",
        "permissions": [
            "view_dashboard",
            "view_projects",
            "view_hr",
            "view_departments",
            "view_job_titles",
            "view_employee_movements",
            "view_leave",
            "edit_leave",
            "view_attendance",
            "clock_attendance",
            "view_approvals",
            "edit_approvals",
        ],
    },
    "Viewer": {
        "description": "只讀",
        "permissions": [
            "view_dashboard",
            "view_finance",
            "view_projects",
        ],
    },
}